### ISSUE TITLE
Backbutton exit my app

### ISSUE THREAD

**Issue by sam2x** [EddyVerbruggen/cordova-plugin-native-keyboard#67]
Hi,

Anyone has experienced a strange behaviour in which the app exit when BackButton is pressed in the "NativeKeyboard" input (keyboard not shown, only messenger) ?  It's similar to a crash but without any warning from the OS and no crash log... 

This is all I have : 

     01-06 15:28:39.795 26748 26748 D ViewRootImpl: ViewPostImeInputStage processKey 0
     01-06 15:28:39.915 26748 26748 D ViewRootImpl: ViewPostImeInputStage processKey 1
     01-06 15:28:39.925  1574  4327 D InputDispatcher: Focus left window: 26748
     01-06 15:28:39.955 26748 26748 W com.facebook.appevents.AppEventsLogger: deactivateApp events are being logged automatically. There's no need to call deactivateApp, this is safe to remove.
     01-06 15:28:39.965 26748 31609 E FA      : Invalid google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI. provided id: 266569744155

Replicate behaviour :

1. Click in the messenger input of the NativeKeyboard
(keyboard appears)
2. Click Backbutton one time 
(keyboard disapear, but focus is on the input messenger)
3. Click Backbutton again 
(app exit...)

**Comment by sam2x** [comment]
Finally a stacktrace : 

01-06 15:34:50.965  4022  4022 W cr_AwContents: Application attempted to call on a destroyed WebView
01-06 15:34:50.965  4022  4022 W cr_AwContents: java.lang.Throwable
01-06 15:34:50.965  4022  4022 W cr_AwContents: 	at org.chromium.android_webview.AwContents.isDestroyed(AwContents.java:364)
01-06 15:34:50.965  4022  4022 W cr_AwContents: 	at org.chromium.android_webview.AwContents.isDestroyedOrNoOperation(AwContents.java:336)
01-06 15:34:50.965  4022  4022 W cr_AwContents: 	at org.chromium.android_webview.AwContents.loadUrl(AwContents.java:413)
01-06 15:34:50.965  4022  4022 W cr_AwContents: 	at com.android.webview.chromium.WebViewChromium.loadUrl(WebViewChromium.java:170)
01-06 15:34:50.965  4022  4022 W cr_AwContents: 	at android.webkit.WebView.loadUrl(WebView.java:908)
01-06 15:34:50.965  4022  4022 W cr_AwContents: 	at org.apache.cordova.engine.SystemWebViewEngine.loadUrl(SystemWebViewEngine.java:275)
01-06 15:34:50.965  4022  4022 W cr_AwContents: 	at org.apache.cordova.CordovaWebViewImpl.loadUrlIntoView(CordovaWebViewImpl.java:128)
01-06 15:34:50.965  4022  4022 W cr_AwContents: 	at org.apache.cordova.CordovaWebViewImpl.loadUrl(CordovaWebViewImpl.java:198)
01-06 15:34:50.965  4022  4022 W cr_AwContents: 	at plugin.google.maps.PluginTileProvider$1.run(PluginTileProvider.java:147)
01-06 15:34:50.965  4022  4022 W cr_AwContents: 	at android.os.Handler.handleCallback(Handler.java:739)
01-06 15:34:50.965  4022  4022 W cr_AwContents: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-06 15:34:50.965  4022  4022 W cr_AwContents: 	at android.os.Looper.loop(Looper.java:148)
01-06 15:34:50.965  4022  4022 W cr_AwContents: 	at android.app.ActivityThread.main(ActivityThread.java:7331)
01-06 15:34:50.965  4022  4022 W cr_AwContents: 	at java.lang.reflect.Method.invoke(Native Method)
01-06 15:34:50.965  4022  4022 W cr_AwContents: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
01-06 15:34:50.965  4022  4022 W cr_AwContents: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by sam2x** [comment]
My assumption was right. Solved this by overwritting the MainActivity.java :

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (keyCode == KeyEvent.KEYCODE_BACK) {
           // do nothing 
           return true;
        }
        return super.onKeyDown(keyCode, event);
    }
