### ISSUE TITLE
add plugin with license to project fails

### ISSUE THREAD

**Issue by pcvengros** [EddyVerbruggen/cordova-plugin-native-keyboard#92]
cordova-android 7.1.2
cordova 8.1.2
---
without android platform added to project I have added keyboard plugin with license
after that I have added android platform: cordova platform add android

result:
Installing "cordova-plugin-native-keyboard" for android
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-native-keyboard': TypeError [ERR_INVALID_ARG_TYPE]: Uh oh!
The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:1088:7)

**Comment by pcvengros** [comment]
workaround for now - add plugin to project without license - do search&replace for word "TRIAL" and replace it with License number :)...

**Comment by pcvengros** [comment]
please see my PR: https://github.com/EddyVerbruggen/cordova-plugin-native-keyboard/pull/93

**Comment by dmastag** [comment]
I tried using your PR by doing
`cordova plugin add https://github.com/securCom/cordova-plugin-native-keyboard.git`

And then running
`cordova platform add android@7.1.2`

But I am still getting the following
```
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-native-keyboard': TypeError [ERR_INVALID_ARG_TYPE]: Uh oh!
The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.resolve (path.js:161:7)
```

**Comment by pcvengros** [comment]
What cordova version?


> I tried using your PR by doing
> `cordova plugin add https://github.com/securCom/cordova-plugin-native-keyboard.git`
> 
> And then running
> `cordova platform add android@7.1.2`
> 
> But I am still getting the following
> 
> ```
> Error during processing of action! Attempting to revert...
> Failed to install 'cordova-plugin-native-keyboard': TypeError [ERR_INVALID_ARG_TYPE]: Uh oh!
> The "path" argument must be of type string. Received type undefined
>     at validateString (internal/validators.js:125:11)
>     at Object.resolve (path.js:161:7)
> ```
> It looks like it works if using cordova-android 7.1.4 but I have this problem in it that prevents me to update
> [apache/cordova-android#599](https://github.com/apache/cordova-android/issues/599)

**Comment by dmastag** [comment]
I am on the latest 8.1.2
Happy to say that my build is working as intended.

So android@7.1.2 not working with your pull request
android@7.1.4 is working fine

**Comment by Panfred** [comment]
Hello,

i still have the same problem also with android@7.1.4 and cordova 8.1.2. 
Installing with cordova plugin add cordova-plugin-native-keyboard i get:
Uh oh!
The "path" argument must be of type string

Thanks 
Francesco
