### ISSUE TITLE
Error installing plugin on Android

### ISSUE THREAD

**Issue by jscuba** [EddyVerbruggen/cordova-plugin-native-keyboard#95]
I followed the instructions in the readme to setup the demo on Android.

cordova -v
8.1.2 (cordova-lib@8.1.1)
platform version: cordova-android@^7.1.4

> cordova plugin add cordova-plugin-native-keyboard

Installing "cordova-plugin-native-keyboard" for android
Android Studio project detected
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-native-keyboard': CordovaError: Uh oh!
"/home/user/Projects/nativekeyboardtest/platforms/android/app/src/main/assets/fonts/fontawesome-webfont.ttf" already exists!
    at copyNewFile (/home/user/Projects/nativekeyboardtest/platforms/android/cordova/lib/pluginHandlers.js:259:45)
    at install (/home/user/Projects/nativekeyboardtest/platforms/android/cordova/lib/pluginHandlers.js:43:17)
    at ActionStack.process (/home/user/Projects/nativekeyboardtest/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/home/user/Projects/nativekeyboardtest/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/home/user/Projects/nativekeyboardtest/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at /home/user/Projects/nativekeyboardtest/platforms/android/cordova/Api.js:247:74
    at _fulfilled (/home/user/Projects/nativekeyboardtest/platforms/android/cordova/node_modules/q/q.js:834:54)
    at /home/user/Projects/nativekeyboardtest/platforms/android/cordova/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/home/user/Projects/nativekeyboardtest/platforms/android/cordova/node_modules/q/q.js:796:13)
    at /home/user/Projects/nativekeyboardtest/platforms/android/cordova/node_modules/q/q.js:556:49
Uh oh!

I fixed this by removing the following from plugin.xml:

    
    <source-file src="src/android/assets/fonts/fontawesome-webfont.ttf" target-dir="assets/fonts" />
    <source-file src="src/android/assets/fonts/ionicons.ttf" target-dir="assets/fonts" />
    <config-file target="res/values/nativekeyboard.xml" parent="/*">
      <string name="NativeKeyboardPluginLicense">$LIC_ANDROID</string>
      <string name="NativeKeyboardPluginLicenseAlt">$LICENSE</string>
    </config-file>

**Comment by pcvengros** [comment]
please try: https://github.com/EddyVerbruggen/cordova-plugin-native-keyboard/pull/94

**Comment by okmebutton** [comment]
Yes, that plugin.xml works.

**Comment by jscuba** [comment]
Yes, that plugin.xml works.
