### ISSUE TITLE
Android can't install

### ISSUE THREAD

**Issue by guiluigi** [EddyVerbruggen/cordova-plugin-native-keyboard#99]
i just run this command and thats the feedback:

cordova plugin add cordova-plugin-native-keyboard --variable LICENSE=(mylicensehere)
Installing "cordova-plugin-native-keyboard" for android
Android Studio project detected
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-native-keyboard': TypeError [ERR_INVALID_ARG_TYPE]: Uh oh!
The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:166:7)
    at copyNewFile (C:\xampp\htdocs\tvcel\platforms\android\cordova\lib\pluginHandlers.js:258:28)
    at install (C:\xampp\htdocs\tvcel\platforms\android\cordova\lib\pluginHandlers.js:43:17)
    at ActionStack.process (C:\xampp\htdocs\tvcel\platforms\android\cordova\node_modules\cordova-common\src\ActionStack.js:56:25)
    at PluginManager.doOperation (C:\xampp\htdocs\tvcel\platforms\android\cordova\node_modules\cordova-common\src\PluginManager.js:114:20)
    at PluginManager.addPlugin (C:\xampp\htdocs\tvcel\platforms\android\cordova\node_modules\cordova-common\src\PluginManager.js:144:17)
    at C:\xampp\htdocs\tvcel\platforms\android\cordova\Api.js:247:74
    at _fulfilled (C:\xampp\htdocs\tvcel\platforms\android\cordova\node_modules\q\q.js:834:54)
    at C:\xampp\htdocs\tvcel\platforms\android\cordova\node_modules\q\q.js:863:30
Uh oh!
The "path" argument must be of type string. Received type undefined

a plugin folder is created, but in xml there is nothing

**Comment by EddyVerbruggen** [comment]
From the looks of it, it's a Cordova issue.. and Googling the message reveals https://github.com/j3k0/cordova-plugin-purchase/issues/756

**Comment by dmastag** [comment]
@EddyVerbruggen isn't this the same with https://github.com/EddyVerbruggen/cordova-plugin-native-keyboard/issues/92 ?
Also, the guy made a PR for a proposed fix
